version: '3.8'
services:
  xlp:
    #build: XLP/
    #container_name: XLP_GENERATOR
    image: usatpath01/xlp-generator:v1
    privileged: true
    pid: host
    #cgroupns: host
    volumes:
      - /boot/config-6.2.0-39-generic/boot/config-6.2.0-39-generic:ro
      - /sys/kernel/debug/:/sys/kernel/debug/
    depends_on:
      - collector_server
    deploy:
      replicas: 1
      placement:
        #constraints: [node.role == worker]
        constraints: [node.hostname == worker-node-2]
    #networks:
    #  - mynetwork

  collector_server:
    #build:
    #  context: XLP_COLLECTOR/
    #container_name: XLP_COLLECTOR
    image: usatpath01/xlp-collector:v1
    hostname: xlp_server
    ports:
      - "8086:8086"
    #restart: always
    deploy:
      replicas: 1
      placement:
        #constraints: [node.role == manager]
         constraints: [node.hostname == master-node]
    #networks:
    #  - mynetwork
    
networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.11.0.0/16